apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-devconfig
data:
  PORT: "4001"
  MONGO_URL: "mongodb://admin:password123@mongo-service.dev.svc.cluster.local:27017/user_db?authSource=admin"
  REDIS_URL: "redis://redis-service.dev.svc.cluster.local:6379"
  REDIS_URL: "redis://redis:6379"
