apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PORT: "4001"
  MONGO_URL: "mongodb://admin:password123@mongo-service:27017/user_db?authSource=admin"
  REDIS_URL: "redis://redis-service:6379"
